# Logger Configuration File
#
# Your administrator can make changes to these defaults in this file:
#
#   /etc/iplock/logger/iplock.d/50-iptables-edit.conf
#
# You can make changes using a file in your configuration folder:
#
#   ~/.config/iplock/logger/iptables-edit.conf
#
# To verify the filenames used by the logger:
#
#   iptables-edit --logger-configuration-filenames
#

# For the command line, make it brief
[console]
format=${severity}: ${message}
tty=true

# vim: syntax=dosini
