#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

# Put the iptables logs in a sub-directory
#
IPTABLESLOGDIR=/var/log/iptables
mkdir -p ${IPTABLESLOGDIR}

# some tools may need the `iptables.log` file to exist otherwise they
# fail, so create it here
#
IPTABLESLOG=${IPTABLESLOGDIR}/iptables.log
if test ! -f ${IPTABLESLOG}
then
    touch ${IPTABLESLOG}
    chown syslog:adm ${IPTABLESLOG}
    chmod 640 ${IPTABLESLOG}
fi

# vim: ts=4 sw=4 et nocindent
