#!/bin/sh
#
# Script used to quickly check out the firewall, without having to remember
# all the options. You must use sudo to run this script:
#
#    sudo showfw
#

IPTABLES=iptables
TYPE=filter
CHAIN=
while test ! -z "$1"
do
	case "$1" in
	"-4")
		IPTABLES=iptables
		;;

	"-6")
		IPTABLES=ip6tables
		;;

	"--filter")
		TYPE=filter
		;;

	-l|"--line-numbers")
		LINE_NUMBERS="--line-numbers"
		;;

	"--mangle")
		TYPE=mangle
		;;

	"--nat")
		TYPE=nat
		;;

	"--raw")
		TYPE=raw
		;;

	"--security")
		TYPE=security
		;;

	-h|"--help")
		echo "Usage: sudo `basename $0` [-4|-6] [--filter|--nat] [--line-numbers] [--help]"
		echo
		echo "  -4                    to display the IPv4 tables, this is the default"
		echo "  -6                    to display the IPv6 tables"
		echo "  --filter              to display the filter table, this is the default"
		echo "  -h | --help           print out this help screen"
		echo "  -l | --line-numbers   show line numbers (rule position)"
		echo "  --mangle              to display the mangle table"
		echo "  --nat                 to display the nat table"
		echo "  --raw                 to display the raw table"
		exit 0
		;;

	"-"*)
		echo "error: unsupported command line option $1"
		echo "error: try --help for more information."
		exit 1
		;;

	*)
		CHAIN=$1
		;;

	esac
	shift
done

# Save the content in a file so that way we do not block the firewall while
# looking at the output (the one drawback is that you have to wait for the
# entire set to be output before seeing anything)
#
OUTPUT_DIR="/run/user/0"
mkdir -p "${OUTPUT_DIR}"
chown root:root "${OUTPUT_DIR}"
chmod 600 "${OUTPUT_DIR}"
OUTPUT="${OUTPUT_DIR}/iprules.txt"
rm -rf "${OUTPUT}"
touch "${OUTPUT}"
chown root:root "${OUTPUT}"
chmod 600 "${OUTPUT}"
${IPTABLES} -t ${TYPE} -L ${CHAIN} -nvx ${LINE_NUMBERS} > "${OUTPUT}"
less -S "${OUTPUT}"
rm -rf "${OUTPUT}"
